spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pvms?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 144972wzy
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # redis配置
  redis:
    port: 6379
    connect-timeout: 5000
    password: 2943808697wzy
    host: 124.223.67.210
    database: 1
    lettuce:
      shutdown-timeout: 100
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del_flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#支付宝配置
alipay:
  protocol: https
  gatewayHost: https://openapi.alipaydev.com/gateway.do
  signType: RSA2
  app-id: 2021000120611424
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmqnIrmyAkdCiO7/V4ra+sBRRoy/Nw+vZ3J8g5fJChbawJ+0Mn14TZult0WFwtgS9jqI1PEEOOAJHewXIRk6fSGMr/74uA5rw1C87XxGJpUzK1zVD8XgWG7Pv23LYdMU8Qd2KvgrLXc1+6M1ZEZ7ld3HAu4L90Bq11/PNyFRIpNgNqZWAuUHodOia5GqUBD86iqqGwSBwb8acsgPXaTleIAAdUaT5KZd8NCMaQd2Yl9dgIui9VgnsV6iDUyujMDIEhD52/yTC1BNXjCf99S1fmeRzuHQHyrQw07JMfavGg/9nOYPB2gENu2zOXJBdQo5WZC9Zx0coFFoOmp3szPLm9wIDAQAB
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCoRCZGxtPhr2bAPBA9eW/0NM/wbzwpOFAz91RiAcYh7FzofGqfZCukax6d54LfbYt7iOf9ooqJAKuiSGFaBqAItsIy4yFxLo8oZXSoX8R22Bfo5s7ngWH75I7070tXG7pYUeJC/GtoaRqkaJ9GggbUy3dGQmZ40LlTO/l0b/z/ap+ka8yPByHCx10r/4lPg0zADnMAPdXtfFP+mbL7Z+k6BJxdUr+lOirXOtKxywGLXXRgjQHhX/+K+M4eQwi63bReQmoUBMpKkmHbxZnpdP0mqDdV/q2UIuPqwy8DSQuHKJ1BgdGKhvOBNVDli8OtICC68Ok5j9vXDk2frB9a7p1DAgMBAAECggEAP7EkJ/BE7Y1+QE+7+fkIlpCTETiZtiSZv0HkkACJ5fdZJ6tIlLLPDjp56V1jnX0Sqh0la01mUPuO/CuXpgMR+pprIeX1l6j/CVR19vHhJPcg/ci4EstXsohOUIpvozZcr+e21JJFec0nB4qOl5rKSSwHJvIlZZ/kNoxiHV/yjR9J8vhSphCJDUqEziBbBGG9VF6jNqnREAJmXbUGZXOeaFhXX539gl7UmtFVtw4c0pfO6eOxMOZcqlFGuSWD5H+kihk1/EOCRUCoH5ZXZRTM0kTtdBzzSsW31UYEYe0cz/gTotlEZaAl/Oy5qoZ5ncWmcoO0iO5wmciz6AEU4TDz+QKBgQDmuq0liNXhZ5BdI9HSxnUuSxeXyD7PaGq5omhldy4ZjntZJCufI0bdOAXU2JRnLSCtNiWQ9wLHN7BR5dyvrjFgGbMCaOsOchUpOiFOUx50gcT7dE6V43KkkbFD2ExhP3C+RFrmzIETlDBN9A3AIsdrZi1Uc9VaXJ/6KqUi5GNbXwKBgQC6shko7JZfY6vMENXJuOuXo75hjpvd2g6Ivkwx3X2k0rudesBPkmgh5q6ADDcBuP4MwRiOhDmEuaJb2n0FDr3sfvORGNBq1rcEjkxEyECTE5mAs/pWn1SndpCtvEsJEMHARJs822MYpFn3nBh03lNB3NZp/aQIzDi1TQnoaLzsnQKBgFm50se79ODZM2zlFx3Oi5dbIGuoNbTWuFpEbDC5LjZGEHXT+RrDzzUMKkhhiSSuifySB/3d8Tij0W+n4jB3nz/t/o07W92cQ9pqfrVE4Z0RMhdPXZgwgU66UaM+pEVVNHTphCgo8zE3+aj29bn4THDZpVsoSJoBVz0kBGATTQglAoGBAKaOKroCz2hMQEDup/utuKhw0XCxTEaQubSuqMU3x1abFfu5PgX/JF1SMk1UGGK2CheQ0Pqb5cCN59WwRyaS70ckPuEsVQtrgJ1U4Z/fUxSjQKe8aNKMlHZN5WbJe9ubkm6YBjI1uuOKBCVNodfpXDd+795hBM1AfDrqfrNTdXBVAoGBAJ9wW90HQjW4uk26fEzCqYSDvFeIJp2t+kmsq4OE4KlzJHUTKJB1/hRbJyOnSEftudpfjUfwJCokfb5uvOopfB9hElLA+vixx8a2ddZwODF7FAfc0a3bCyEsfmvkQDC+/okMzCNUPRVd6c7rIzeJxM4zzYp1GR9WdrEZzBhWXW1L
  #订单支付回调地址
  orderPayNotifyUrl: https://127.0.0:8080/alipay/callback
server:
  port: 8001